# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('www', '0002_delete_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('credit', models.IntegerField(default=0, null=True)),
                ('password', models.CharField(default='123456', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=200)),
                ('cPhone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('saghf', models.IntegerField(default=9223372036854775807)),
                ('percent', models.IntegerField()),
                ('expiration', models.DateField()),
                ('cPhone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='www.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sendCost', models.IntegerField()),
                ('orderDescription', models.TextField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('totalCost', models.IntegerField()),
                ('cPhone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('addr', models.CharField(max_length=200)),
                ('saatKari', models.CharField(max_length=11)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='foods',
            name='resName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Restaurant'),
        ),
    ]
