# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20171026_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='saghf',
            field=models.IntegerField(default=922337203685477580),
        ),
    ]
