# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_auto_20171026_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='saghf',
            field=models.IntegerField(default=-1),
        ),
    ]
